openapi: 3.0.3
info:
  title: Individuals Reliefs (MTD)
  description: "The following groups of endpoints are stateful in the Sandbox:\n*\
    \ [Relief Investments](#tag/Relief-Investments)\n* [Other Reliefs](#tag/Other-Reliefs)\n\
    * [Foreign Reliefs](#tag/Foreign-Reliefs)\n* [Pensions Reliefs](#tag/Pensions-Reliefs)\n\
    * [Charitable Givings](#tag/Charitable-Givings)\n\n# Send fraud prevention data\n\
    HMRC monitors transactions to help protect your customers' confidential data from\
    \ criminals and fraudsters. \n<div class=\"govuk-warning-text warning-icon-fix\"\
    >\n  <span class=\"govuk-warning-text__icon warning-icon-ui-fix\" aria-hidden=\"\
    true\">!</span>\n  <strong class=\"govuk-warning-text__text\">\n    <span class=\"\
    govuk-warning-text__assistive\">Warning</span>\n    You are required by law to\
    \ submit header data for this API. This includes all associated APIs and endpoints.\n\
    \  </strong>\n</div>\n\n[Check the data you need to send](/guides/fraud-prevention/).\
    \ You can also use the [Test API](/api-documentation/docs/api/service/txm-fph-validator-api/1.0)\
    \ during initial development and as part of your quality assurance checks.\n\n\
    # Mapping APIs to Self Assessment tax return forms\nSome parameters in this API\
    \ map to box numbers in one or more Self Assessment tax return forms. To learn\
    \ more and to download this mapping information as a CSV file, go to [income-tax-mtd-changelog/mapping](https://github.com/hmrc/income-tax-mtd-changelog?tab=readme-ov-file#mapping-apis-to-self-assessment-tax-return-forms)\
    \ on GitHub.\n\n# Changelog\nYou can find the changelog in the [income-tax-mtd-changelog](https://github.com/hmrc/income-tax-mtd-changelog/#readme)\
    \ on GitHub.\n\n# Support\n\n* Direct reports of bugs or errors in Production\
    \ or Sandbox code, or queries about HMRC business functionality (such as how a\
    \ specific field is used by HMRC or why it is needed) to the [Software Development\
    \ Support Team (SDST)](https://developer.service.hmrc.gov.uk/developer/support).\n\
    * Send queries or feedback related to the design of the APIs (including recommended\
    \ changes) using the [income-tax-mtd-changelog](https://github.com/hmrc/income-tax-mtd-changelog/issues)\
    \ GitHub page.\n* <a href=\"/contact/report-technical-problem?newTab=true&service=api-documentation-frontend\"\
    \ target=\"_blank\">Is this page not working properly? (opens in new tab)</a>\n"
  version: "1.0"
servers:
- url: https://test-api.service.hmrc.gov.uk
  description: Sandbox
- url: https://api.service.hmrc.gov.uk
  description: Production
tags:
- name: Relief Investments
  description: Resources relating to an individual's relief investments
- name: Other Reliefs
  description: Resources relating to an individual's other reliefs
- name: Foreign Reliefs
  description: Resources relating to an individual's foreign reliefs
- name: Pensions Reliefs
  description: Resources relating to an individual's pensions reliefs
- name: Charitable Givings
  description: Resources relating to an individual's charitable givings
paths:
  /individuals/reliefs/investment/{nino}/{taxYear}:
    get:
      summary: Retrieve Relief Investments
      security:
      - User-Restricted:
        - read:self-assessment
    put:
      summary: Create and Amend Relief Investments
      security:
      - User-Restricted:
        - write:self-assessment
    delete:
      summary: Delete Relief Investments
      security:
      - User-Restricted:
        - write:self-assessment
  /individuals/reliefs/other/{nino}/{taxYear}:
    get:
      summary: Retrieve Other Reliefs
      security:
      - User-Restricted:
        - read:self-assessment
    put:
      summary: Create and Amend Other Reliefs
      security:
      - User-Restricted:
        - write:self-assessment
    delete:
      summary: Delete Other Reliefs
      security:
      - User-Restricted:
        - write:self-assessment
  /individuals/reliefs/foreign/{nino}/{taxYear}:
    get:
      summary: Retrieve Foreign Reliefs
      security:
      - User-Restricted:
        - read:self-assessment
    put:
      summary: Create and Amend Foreign Reliefs
      security:
      - User-Restricted:
        - write:self-assessment
    delete:
      summary: Delete Foreign Reliefs
      security:
      - User-Restricted:
        - write:self-assessment
  /individuals/reliefs/pensions/{nino}/{taxYear}:
    get:
      summary: Retrieve Pensions Reliefs
      security:
      - User-Restricted:
        - read:self-assessment
    put:
      summary: Create and Amend Pensions Reliefs
      security:
      - User-Restricted:
        - write:self-assessment
    delete:
      summary: Delete Pensions Reliefs
      security:
      - User-Restricted:
        - write:self-assessment
  /individuals/reliefs/charitable-giving/{nino}/{taxYear}:
    get:
      summary: Retrieve Charitable Giving Tax Relief
      security:
      - User-Restricted:
        - read:self-assessment
    put:
      summary: Create and Amend Charitable Giving Tax Relief
      security:
      - User-Restricted:
        - write:self-assessment
    delete:
      summary: Delete Charitable Giving Tax Relief
      security:
      - User-Restricted:
        - write:self-assessment
components:
  securitySchemes:
    User-Restricted:
      type: oauth2
      description: "HMRC supports OAuth 2.0 for authenticating [User-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints)\
        \ API requests"
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            write:self-assessment: Grant write access
            read:self-assessment: Grant read access
